version: '3'

services:

  nginx:
    # Use jwilder/nginx-proxy but with slight changes
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Mount self signed https certificates for testing environment
      # - ${HOME}/.gdev/certs:/etc/nginx/certs:ro
    network_mode: "bridge"
